# Generated by Django 5.1.5 on 2025-02-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_symbol',
            field=models.CharField(help_text='Symbol of the token (e.g., BTC, ETH)', max_length=20, unique=True, verbose_name='Token Symbol'),
        ),
    ]
